spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: http://localhost:8091/
        predicates:
        - Path=/product/**
      - id: orderModule
        uri: http://localhost:8092/
        predicates:
        - Path=/order/**
      - id: invoiceModule
        uri: http://localhost:8093/
        predicates:
        - Path=/invoice/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     prefer-ip-address: true
     
server:
  port: 8989
